name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00 UTC
  workflow_dispatch:      # Allows manual triggering too

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make dummy change
        run: |
          echo "// 🤖 Updated on $(date)" >> update.md

      - name: Configure Git
        run: |
          git config user.name "Tony Kariuki"
          git config user.email "akk85@cornell.edu"

      - name: Commit and push
        run: |
          git add update.md
          git commit -m "🔥 job commit incase of missed commit"
          git push
