name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout base branch (tony-dev)
        uses: actions/checkout@v3
        with:
          ref: tony-dev

      - name: Set PR branch name
        run: echo "PR_BRANCH=tony-pr-$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create new branch
        run: |
          git checkout -b $PR_BRANCH

      - name: Make dummy change
        run: |
          mkdir -p .daily-log
          echo "// 🤖 Updated on $(date) - $RANDOM" >> .daily-log/$(date +%Y-%m-%d).md

      - name: Configure Git
        run: |
          git config user.name "Tony Kariuki"
          git config user.email "akk85@cornell.edu"

      - name: Commit and push
        run: |
          git add .daily-log/ update.md
         git commit -m "🔥 Daily streak commit" || echo "No changes to commit"
          git push origin $PR_BRANCH

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.PR_BRANCH }}
          base: main
          title: "📌 Daily Update - ${{ env.PR_BRANCH }}"
          body: |
            Automated daily PR from ${{ env.PR_BRANCH }} to main.
          delete-branch: false
