name: Cronjob Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at 00:00 UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up branch name
        id: vars
        run: echo "BRANCH=daily-update-$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Make dummy change
        run: |
          echo "// 🤖 Updated on $(date) - $RANDOM" >> update.md

      - name: Configure Git
        run: |
          git config user.name "Tony Kariuki"
          git config user.email "akk85@cornell.edu"

      - name: Commit and push to new branch
        run: |
          git checkout -b $BRANCH
          git add update.md
          git commit -m "🔥 Daily streak commit"
          git push origin $BRANCH

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH }}
          title: "📌 Daily Update - ${{ env.BRANCH }}"
          body: |
            Automated PR for daily contribution. Please review and merge when ready.
          base: main
          delete-branch: true  # This will delete the branch after you manually merge the PR
