name: "Daily Maintenance"

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Touch hidden file
        run: touch .keep

      - name: Configure Git
        run: |
          git config user.name "Tony Kariuki"
          git config user.email "dev@tonykariuki.com"

      - name: Random commit message + push
        run: |
          COMMIT_MSGS=("minor update" "refactor" "tweak" "fix typo" "update logs")
          MSG=${COMMIT_MSGS[$RANDOM % ${#COMMIT_MSGS[@]}]}
          git add .keep
          git commit -m "$MSG"
          git push
